CREATE TABLE survey(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  [Beach] TEXT NOT NULL,
  [Start Time] TIME NOT NULL,
  [Location] TEXT NOT NULL,
  [Method] TEXT NOT NULL,
  [Date] DATE NOT NULL,
  [Water Depth] DOUBLE NOT NULL,
  [Tide] TEXT NOT NULL,
  [Duration] INTEGER NOT NULL,
  [Distance] DOUBLE NOT NULL,
  [Slope] DOUBLE NOT NULL
);
